### ISSUE TITLE
Documentation example error in code: examples_transferentropy.md

### ISSUE THREAD

**Issue by proudindiv** [JuliaDynamics/Associations.jl#366]
When testing the examples in the dev documentation:

[Transfer entropy](https://juliadynamics.github.io/CausalityTools.jl/dev/examples/examples_transferentropy/#examples_transferentropy):  [Reproducing-Schreiber-(2000))](https://github.com/JuliaDynamics/CausalityTools.jl/blob/main/docs/src/examples/examples_transferentropy.md#reproducing-schreiber-2000); [github](https://github.com/JuliaDynamics/CausalityTools.jl/blob/main/docs/src/examples/examples_transferentropy.md) lines 131-132, also at 178-179.

The two `scatterlines` `lw = 1.5` arguments are invalid.
![scatterlinesInvalid2](https://github.com/JuliaDynamics/CausalityTools.jl/assets/7218387/2dd31cd9-7bc7-4550-ba6c-c59bc2d2b443)

Refering to [makie](https://docs.makie.org/stable/reference/plots/scatterlines/)  documentation,  if you change the `lw` argument to `strokewidth` it works like the version in your doc:

![scatterlinesFixed](https://github.com/JuliaDynamics/CausalityTools.jl/assets/7218387/15fbd0bf-66da-4851-9f87-aaa93711cdc3)

**Comment by proudindiv** [comment]
![juliaVersion](https://github.com/JuliaDynamics/CausalityTools.jl/assets/7218387/762ed915-f11a-447d-853d-7fb86e60fc45)
![linuxmintVersion](https://github.com/JuliaDynamics/CausalityTools.jl/assets/7218387/80cdecbe-9ed9-49bc-b25e-6bcd5cc9aed2)
![IJuliaVersion](https://github.com/JuliaDynamics/CausalityTools.jl/assets/7218387/1e0c93b8-d11f-4a34-a93d-4262d957e8b9)
![JupyterVersion](https://github.com/JuliaDynamics/CausalityTools.jl/assets/7218387/78b2f84d-cab1-4eb6-a609-edb6a7b0bac2)

**Comment by kahaaga** [comment]
Thanks for reporting this, @proudindiv!

**Comment by kahaaga** [comment]
This example is now fixed [https://juliadynamics.github.io/Associations.jl/stable/examples/examples_associations/#Reproducing-Schreiber-(2000)].
