### ISSUE TITLE
`CETsallisFuruichi` has no valid implementation?

### ISSUE THREAD

**Issue by Datseris** [JuliaDynamics/Associations.jl#371]
I was reading the docs of the conditional entropy because I wanted to apply it to some timeseries, 

https://juliadynamics.github.io/CausalityTools.jl/dev/api/api_conditional_entropy/#CausalityTools.entropy_conditional

and i've noticed that in the table listing compatible outcome spaces, there is none actually compatible with the `CETsallisFuruichi`.

**Comment by Datseris** [comment]
But probably the docs are outdated as they refer to outcome spaces as "probabilities estimators"

**Comment by Datseris** [comment]
@kahaaga perhaps you should open a PR with your updates to bring CausalityTools.jl to ComplexityMeasures.jl v3, and I can try to contribute at some point, as the package isn't really compatible with v3 at the moment.

**Comment by kahaaga** [comment]
@Datseris I'll try to merge most of what I've got within the week, but I'm pretty busy atm, so no guarantees on how fast I can do this. Most of the discrete estimation stuff should be ready, though, so I just have to dive in and find the relevant PRs

**Comment by kahaaga** [comment]
This now works on v3 and is documented with [examples](https://juliadynamics.github.io/Associations.jl/stable/examples/examples_associations/#example_ConditionalEntropyTsallisFuruichi_JointProbabilities_CodifyVariables_UniqueElements).
