### ISSUE TITLE
Conditional Chatterjee coefficient

### ISSUE THREAD

**Issue by kahaaga** [JuliaDynamics/Associations.jl#380]
## Describe the feature you'd like to have

[This paper](https://arxiv.org/pdf/1910.12327
) presents a conditional version of the Chatterjee coefficient (see feature request in #379). [This paper](https://arxiv.org/pdf/2108.06827) presents some more elaborate conditional dependence tests using the measure.

**Comment by Datseris** [comment]
(offtopic) I've taken the liberty to clean up a bit the labels. I also removed the "new" from labels such as "new association measure". The combination of "association measure" with "enhancement" indicates it is a new feature, while "association measure" with "bug" indicates it is a problem with an existing measure.
